### ISSUE TITLE
Line as thumb

### ISSUE THREAD

**Issue by GioPan04** [HannesGitH/squiggly_slider#3]
Android 13's slider uses a line as a thumb. I think this should be the default shape used in this package since (as I understood) it tries to recreate the Android 13's slider.

Example: 
![share_9206252043054651770](https://github.com/HannesGitH/squiggly_slider/assets/29762826/528de9b7-b25e-4f39-b943-618a60ac7e8c)

I think implementing this should be pretty easy since that `SliderTheme` allows you to customize the thumb shape.

I would like to implement it if you are ok with it :)

**Comment by HannesGitH** [comment]
fair point, although as this is not a perfect recreation anyway and leans more towards the normal slider, i think the default thumb shape should stay the way it currently is, as that integrates better design-wise with the rest of most apps.

But feel free to add an additional option like `useLineThumb` that simplifies using your/the A13 theme :)

**Comment by GioPan04** [comment]
Okay thanks. I'll work on it as soon as possible
